config/routes.rb
Rails.application.routes.draw do
  #User routes
  root to: "users#index"
  get "/users", to: "users#index", as: "users"
  get "/users/new", to: "users#new", as: "new_user"
  post "/users", to: "users#create", as: "create_user"
  get "/users/:id", to: "users#show", as: "user"
  get "users/:id/edit", to: "users#edit", as:"user_edit"
  patch "/users/:id", to: "users#update", as: "update_user"
  delete '/users/:id', to: "users#destroy", as: "destroy_user"

  #Sessions
  get "/login", to: "sessions#new"
  get "/logout", to: "sessions#destroy"
  post "/sessions", to: "sessions#create"

  #Comments
  get '/events/:id/comments/new', to: "comments#new", as: "new_comment"
  post '/events/:id/comments/create', to: "comments#create", as: "create_comment"
  get '/comments/:id/edit', to: "comments#edit", as: "edit_comment"
  patch '/comments/:id', to: "comments#update"
  delete '/events/:event_id/comments/:comment_id', to: "comments#destroy", as: "delete_comment"


  #Events
  get "/events", to: "events#index", as: "events"
  get "/events/new", to: "events#new", as: "new_event"
  post "/events", to: "events#create", as: "create_event"
  get "/events/:id", to: "events#show", as: "event"
  get "/events/:id/edit", to: "events#edit", as: "edit_event"
  patch "/events/:id", to: "events#update", as: "update_event"
  delete "/events/:id", to: "events#destroy", as: "delete_event"

  #Attend
  get "/events/:id/attend/new", to: "attendances#new", as: "new_attendance"
  post "/events/:id/attend", to: "attendances#create", as: "create_attendance"


end

app/models/user.rb
class User < ActiveRecord::Base
  validates :email, :password, length:{maximum:40}, presence:true, confirmation:true
  validates :email, uniqueness:true
  validates_confirmation_of :password
  has_secure_password
  has_many :attendances
  has_many :events, through: :attendances
  has_many :comments, dependent: :destroy

  def self.confirm(params)
    @user = User.find_by({email: params[:email]})
    @user.try(:authenticate, params[:password])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    render :index
  end

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.create(user_params)
    if @user.profile_image == ""
      @user.profile_image = "/placeholder.jpg"
    end
    if @user.save
    flash[:notice] = "Welcome to PlanTastic! Your profile has been successfully created!"
    login(@user)
    redirect_to user_path(@user)
    else
    flash[:error] = "Please fill in all required fields (marked with *)"
    redirect_to new_user_path
    end
  end

  def show
    @user = User.find_by_id(params[:id])
    if @user == current_user
      render :show
    else
      redirect_to users_path
    end
  end

  def edit
    @user = User.find_by_id(params[:id])
    if current_user == @user
      render :edit
    else
      redirect_to users_path
    end
  end

  def update
    @user = User.find_by_id(params[:id])
    if current_user == @user
      if @user.update(user_params)
        flash[:notice] = "Successfully Updated!"
        redirect_to @user
      else
        flash[:error] = "Please fill in all required fields (marked with *)"
        redirect_to @user
      end
    end
  end

  def destroy
    @user = User.find_by_id(params[:id])
    @user.destroy
    flash[:error] = "Your profile has been deleted"
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :profile_image, :password, :password_confirmation)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= simple_form_for @user do |f| %>
  <%= f.input :first_name, placeholder: "First Name"%>
  <%= f.input :last_name, placeholder: "Last Name"%>
  <%= f.input :email, placeholder: "email@email.com"%>
  <%= f.input :password, placeholder: "Password"%>
  <%= f.input :password_confirmation, placeholder: "Confirm Password", required: true %>
  <%= f.input :profile_image, placeholder: "www.domain.com/image.jpg" %>
  <%= f.button :submit %>
<% end %>

app/views/users/_forms.html.erb
<%= simple_form_for @user do |f| %>
  <%= f.input :first_name, placeholder: "First Name"%>
  <%= f.input :last_name, placeholder: "Last Name"%>
  <%= f.input :email, placeholder: "email@email.com"%>
  <%= f.input :password, placeholder: "Password"%>
  <%= f.input :password_confirmation, placeholder: "Confirm Password"%>
  <%= f.input :profile_image, placeholder: "www.domain.com/image.jpg" %>
  <%= f.button :submit %>
<% end %>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <h1>Edit</h1>
    <hr>
  </div>
  <div class="row">
    <div class="col-md-6">
      <%= render "form"%>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="jumbotron">
  <div class="container">
    <p>Welcome to,</p><h1 class="display-3">planTastic!</h1> <p>Planning your events just got easier</p>
    <hr>
    <p></p>
    <p class="lead">
      <% if current_user %>
        <%= button_to "Create Event!", new_event_path, :method => "get", class: "btn btn-lg btn-success" %>
      <% else %>
        <%= button_to "Sign Up!", new_user_path, :method => "get", class: "btn btn-lg btn-primary" %>
      <% end %>
    </p>
  </div>
</div>

<div class="container marketing">




  <!-- START THE FEATURETTES -->

  <hr class="featurette-divider">

  <div class="row featurette">
    <div class="col-md-7">
      <h2 class="featurette-heading">Organize your outings. <span class="text-muted">It'll blow your mind.</span></h2>
      <p class="lead">No more confusion about who is going to bring what to your event.</p>
    </div>
    <div class="col-md-5">
      <%= image_tag "party1.jpg", class:"featurette-image img-responsive center-block" %>
    </div>
  </div>

  <hr class="featurette-divider">

  <div class="row featurette">
    <div class="col-md-7 col-md-push-5">
      <h2 class="featurette-heading">Easily create new events. <span class="text-muted">Nice!</span></h2>
      <p class="lead">Forget handmade invitations and snail mail, with planTastic, your friends can RSVP to your event with the click of their mouse!</p>
    </div>
    <div class="col-md-5 col-md-pull-7">
      <%= image_tag "party2.jpg", class:"featurette-image img-responsive center-block" %>
    </div>
  </div>

  <hr class="featurette-divider">

  <div class="row featurette">
    <div class="col-md-7">
      <h2 class="featurette-heading">Keep track of upcoming events. <span class="text-muted">Checkmate.</span></h2>
      <p class="lead">Use your personal profile to keep track of events you're attending.</p>
    </div>
    <div class="col-md-5">
      <%= image_tag "party3.jpg", class:"featurette-image img-responsive center-block" %>
    </div>
  </div>

  <hr class="featurette-divider">

  <!-- /END THE FEATURETTES -->

  <!-- Three columns of text below the carousel -->
  <div class="row">
    <h2>About the creators</h2>
  </div>
  <br>
  <div class="row">
    <div class="col-sm-3">
      <%= image_tag "bryan.jpg", class:"img-circle", size:"140x140"%>
      <h2>Bryan Smith</h2>
      <p>Born in California, raised in Arizona, I'm a one of a kind web developer! I started web development after deciding I needed a change. I thought web development was the best cross between creativity and coding! So far it's been an awesome journey that I've been able to share with the wonderful people to my right.</p>
    </div><!-- /.col-lg-4 -->
    <div class="col-sm-3">
      <%= image_tag "jackie.jpg", class:"img-circle", size:"140x140"%>
      <h2>Jackie Fambrough</h2>
      <p>Born and raised in the Central Valley and currently residing in Oakland. Things I enjoy: web development, jokes, music, food, and friendship. Check out my <a href =“https://github.com/jacquelynfambrough”>GitHub</a> account to see other works I’ve contributed to and created! </p>
    </div><!-- /.col-lg-4 -->
    <div class="col-sm-3">
      <%= image_tag "sarah.jpg", class:"img-circle", size:"140x140"%>
      <h2>Sarah Bannister</h2>
      <p>Born and raised in Eugene, Oregon. I really like nachos, dogs, motorcycles, bad movies (good movies are cool, too) and traveling. I used to be a hairstylist before I decided to follow my dreams of becoming a web developer/UI designer and I couldn't be happier!</p>
    </div><!-- /.col-lg-4 -->
    <div class="col-sm-3">
      <%= image_tag "rene.jpg", class:"img-circle", size:"140x140"%>
      <h2>Rene Arellano</h2>
      <p>An SFSU alumni, I came to the city for an education and stayed for the people, food, and opportunity.  During my residency in SF, I experience the Bay Area influence on the world with the hyphy movement and the share economy.  Accordingly, I am passionate about open source projects that contribute to the greater good.  PlanTastic was a great platform for affecting both.
    </div><!-- /.col-lg-4 -->
  </div><!-- /.row -->

</div>

app/views/users/new.html.erb
<div class="container">
  <div class="col-md-6">
    <div class="row">
      <h1>Sign Up</h1>
    </div>
    <hr>
    <div class="row">
      <%= render "form"%>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container user-container">
  <div class="row">
    <h1>Your Profile</h1>
    <hr>
  </div>
  <div class="row">
    <div class="col-md-4">
      <h3>Welcome, <%= @user.first_name %></h3>
      <hr>
      <%= image_tag @user.profile_image, class: "img-responsive img-circle", size: "340x340"%>
      <hr>
      <table class="table table-striped">
        <tbody>
          <tr>
            <td>First Name:</td>
            <td><%= @user.first_name %></td>
          </tr>
          <tr>
            <td>Last Name:</td>
            <td><%= @user.last_name%></td>
          </tr>
          <tr>
            <td>Email Address:</td>
            <td><%= @user.email%></td>
          </tr>
        </tbody>
      </table>
      <div class="btn-group btn-group-justified" role="group">
        <div class="inner"><%= button_to "Edit Profile", user_edit_path(@user), :method => 'get', class: "btn btn-small btn-success" %></div>
        <div class="inner"><%= button_to "New Event", new_event_path(@user), :method => 'get', class: "btn btn-small btn-primary" %></div>
        <div class="inner"><%= button_to "Delete Profile", destroy_user_path(@user),data: {:confirm=>'Are you sure you want to delete your profile? This cannot be undone.'}, :method => 'delete', class: "btn btn-small btn-danger" %></div>
      </div>
    </div>
    <div class="col-md-8">
      <h3>Attending</h3>
      <hr>
      <% if @user.events.empty? %>
        <p>You currently aren't attending any upcoming events</p>
      <% end %>
      <% else %>
      <% @user.events.each do |t|%>
        <%= image_tag (t.photo), class: "img-responsive img-thumbnail" %>
        <h3><%=link_to "#{t.title}", event_path(t)%></h3>
        <p><%= "#{t.description}" %></p>
        <p>Location: <%= "#{t.location}" %></p>
        <hr>
      <%end%>
    </div>
  </div>
</div>