config/routes.rb
Rails.application.routes.draw do
  #User routes
  root to: "users#index"
  get "/users", to: "users#index", as: "users"
  get "/users/new", to: "users#new", as: "new_user"
  post "/users", to: "users#create", as: "create_user"
  get "/users/:id", to: "users#show", as: "user"
  get "users/:id/edit", to: "users#edit", as:"user_edit"
  patch "/users/:id", to: "users#update", as: "update_user"
  delete '/users/:id', to: "users#destroy", as: "destroy_user"

  #Sessions
  get "/login", to: "sessions#new"
  get "/logout", to: "sessions#destroy"
  post "/sessions", to: "sessions#create"

  #Comments
  get '/events/:id/comments/new', to: "comments#new", as: "new_comment"
  post '/events/:id/comments/create', to: "comments#create", as: "create_comment"
  get '/comments/:id/edit', to: "comments#edit", as: "edit_comment"
  patch '/comments/:id', to: "comments#update"
  delete '/events/:event_id/comments/:comment_id', to: "comments#destroy", as: "delete_comment"


  #Events
  get "/events", to: "events#index", as: "events"
  get "/events/new", to: "events#new", as: "new_event"
  post "/events", to: "events#create", as: "create_event"
  get "/events/:id", to: "events#show", as: "event"
  get "/events/:id/edit", to: "events#edit", as: "edit_event"
  patch "/events/:id", to: "events#update", as: "update_event"
  delete "/events/:id", to: "events#destroy", as: "delete_event"

  #Attend
  get "/events/:id/attend/new", to: "attendances#new", as: "new_attendance"
  post "/events/:id/attend", to: "attendances#create", as: "create_attendance"


end

app/views/shared/_footer.html.erb
<!-- footer -->
<div class="container">
  <div class="row">
    <hr class="featurette-divider">
    <div class="footer navbar-fixed-bottom">
      <footer>
        <p class="pull-right"><a href="#">Back to top</a></p>
        <p>&copy; 2016 planTastic, Inc. </p>
      </footer>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<!-- Basic Navbar -->
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "planTastic", users_path, class: "navbar-brand" %>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if current_user %>
          <li><%= link_to "My Profile", user_path(current_user) %></li>
          <li><%= link_to "Create Event", new_event_path %></li>
        <% else %>
          <li><%= link_to "Create Account", new_user_path %></li>
        <% end %>
        <li><%= link_to "See Events", events_path%></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li><%= link_to "Log Out", logout_path %></li>
        <% else %>
          <li><%= link_to "Log In", login_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>