config/routes.rb
Rails.application.routes.draw do
  #User routes
  root to: "users#index"
  get "/users", to: "users#index", as: "users"
  get "/users/new", to: "users#new", as: "new_user"
  post "/users", to: "users#create", as: "create_user"
  get "/users/:id", to: "users#show", as: "user"
  get "users/:id/edit", to: "users#edit", as:"user_edit"
  patch "/users/:id", to: "users#update", as: "update_user"
  delete '/users/:id', to: "users#destroy", as: "destroy_user"

  #Sessions
  get "/login", to: "sessions#new"
  get "/logout", to: "sessions#destroy"
  post "/sessions", to: "sessions#create"

  #Comments
  get '/events/:id/comments/new', to: "comments#new", as: "new_comment"
  post '/events/:id/comments/create', to: "comments#create", as: "create_comment"
  get '/comments/:id/edit', to: "comments#edit", as: "edit_comment"
  patch '/comments/:id', to: "comments#update"
  delete '/events/:event_id/comments/:comment_id', to: "comments#destroy", as: "delete_comment"


  #Events
  get "/events", to: "events#index", as: "events"
  get "/events/new", to: "events#new", as: "new_event"
  post "/events", to: "events#create", as: "create_event"
  get "/events/:id", to: "events#show", as: "event"
  get "/events/:id/edit", to: "events#edit", as: "edit_event"
  patch "/events/:id", to: "events#update", as: "update_event"
  delete "/events/:id", to: "events#destroy", as: "delete_event"

  #Attend
  get "/events/:id/attend/new", to: "attendances#new", as: "new_attendance"
  post "/events/:id/attend", to: "attendances#create", as: "create_attendance"


end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :attendances
  has_many :users, through: :attendances
  has_many :comments

  validates :location, :title, presence:true

  extend FriendlyId
  friendly_id :title, use: :slugged


    # adds an error if birth date is in the future
  def future_event?
    if event_date < Date.today
      errors.add(:event_date, "Must be in the future")
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @event = Event.all
    @user = User.find_by_id(params[:id])
    render :index
  end

  def show
    @event = Event.find_by_slug(params[:id])
    @comments = @event.comments
    render :show
  end

  def new
    @event = Event.new
    @user = User.find_by_id(params[:id])
  end

  def create
    @event = Event.new(event_params)
    @event.user_id = current_user.id
    @user = User.find_by_id(params[:id])
    if @event.photo == ""
      @event.photo = "/placeholder.jpg"
    end
    if @event.save
      flash[:notice] = "Let's party! Your event has been successfully created!"
      redirect_to event_path(@event)
    else
      flash[:error] = "Please fill in all required fields (marked with *)"
      redirect_to new_event_path
    end
  end

  def edit
    @event = Event.find_by_slug(params[:id])
    @user = User.find_by_id(params[:id])
    render :edit
  end

  def update
    @event = Event.find_by_slug(params[:id])
    if @event.update(event_params)
      redirect_to event_path(@event)
    else
      flash[:error] = "There was a problem saving your changes"
      redirect_to event_path(@event)
    end
  end

  def destroy
    @event = Event.find_by_slug(params[:id])
    @event.destroy
    redirect_to events_path
  end

  private

  def event_params
    params.require(:event).permit(:title, :location, :event_date, :event_time, :description, :photo, :slug)
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= simple_form_for @event do |f| %>
  <%= f.input :title, placeholder: "Title"%>
  <%= f.input :location, placeholder: "Location", :input_html => { :id => 'locationTextField' } %>
  <%= f.input :photo, {placeholder: "Image URL", class: "form-control "} %>
  <%= f.input :description, placeholder: "Description" %>
  <%= f.input :event_date, placeholder: "Date", id: "datepicker"%>
  <%= f.input :event_time, placeholder: "Time"%>
  <%= f.button :submit %>
<% end %>

app/views/events/_forms.html.erb
<%= simple_form_for @event do |f| %>
  <%= f.input :title, placeholder: "Title"%>
  <%= f.input :location, placeholder: "Location", :input_html => { :id => 'locationTextField' } %>
  <%= f.input :photo, {placeholder: "Image URL", class: "form-control "} %>
  <%= f.input :description, placeholder: "Description" %>
  <%= f.input :event_date, placeholder: "Date"%>
  <%= f.input :event_time, placeholder: "Time"%>
  <%= f.button :submit %>
<% end %>

app/views/events/edit.html.erb
<script>
var ready;
ready = function() {
    var input = document.getElementById('locationTextField');
    var autocomplete = new google.maps.places.Autocomplete(input);
  }
$(document).ready(ready);
$(document).on('turbolinks:load', ready);

google.maps.event.addDomListener(window, 'load', init);

</script>

<div class="container">
  <div class="row">
    <h1>Edit your Event</h1>
    <hr>
  </div>
  <div class="row">
    <div class="col-md-6">
      <%= render "form" %>
    </div>
  </div>  
</div>

app/views/events/index.html.erb
<div class="container">
  <div class="row">
    <h1>Welcome to the Events page!</h1>
    <hr>
  </div>
  <div class="row">
    <% @event.each do |t|%>
      <div class="row event">
        <div class="col-md-4">
          <%= image_tag (t.photo), class: "img-responsive img-thumbnail" %>
        </div>
        <div class="col-md-6">
          <h3><%=link_to "#{t.title}", event_path(t)%></h3>
          <p><%= "#{t.description}" %></p>
          <p>Location: <%= "#{t.location}" %></p>
        </div>
      </div>
    <%end%>
  </div>
</div>

app/views/events/new.html.erb
<script>
var ready;
ready = function() {
    var input = document.getElementById('locationTextField');
    var autocomplete = new google.maps.places.Autocomplete(input);
  }
$(document).ready(ready);
$(document).on('turbolinks:load', ready);

google.maps.event.addDomListener(window, 'load', init);

</script>

<div class="container">
  <div class="row">
    <h1>Create an Event</h1>
  </div>
  <hr>
  <div class="row">
    <div class="col-md-4">
      <%= image_tag "party3.jpg", class:"img-responsive img-thumbnail"%>
    </div>
    <div class="col-md-8">
      <%= render "form" %>
    </div>

  </div>
</div>

app/views/events/show.html.erb
<div class="container event-container">
  <div class="row">
    <h1 class="eventTitle"><%= @event.title %></h1>
    <hr>
  </div>
  <div class="row">
    <div class="col-md-6">
        <%= image_tag (@event.photo), class: "img-responsive img-thumbnail" %>
      <div class="group btn-group">
        <% if current_user%>
          <div class="inner"><%= button_to "Edit", edit_event_path(@event), :method => "get", class: "btn btn-small btn-success"%></div>
          <div class="inner"><%= button_to "Delete Event", delete_event_path, data: {:confirm=>'Are you sure you want to delete this event?'}, :method => "delete", class: "btn btn-small btn-danger" %></div>
          <div class="inner"><%= button_to "Attend", new_attendance_path(@event), :method => "get", class: "btn btn-small btn-primary" %></div>
        <% else %>
          <%= button_to "Login", login_path, :method => "get", class: "btn btn-small btn-primary" %>
        <% end %>
      </div>
        <h2>What?</h2>
        <p><%= @event.description%></p>
        <hr>
        <h2>Where?</h2>
        <p><%= @event.location%></p>
        <hr>
        <h2>When?</h2>
        <p>Date: <%= @event.event_date %></p>
        <p>Time: <%= @event.event_time %></p>
    </div>

    <div class="col-md-6">
      <h1>Comments:</h1>
      <hr>
      <% if current_user %>
        <% @comments.each do |comment|%>
          <% commenter = User.find_by_id(comment.user_id)%>
          <h4><%= commenter.first_name%>:</h4>
          <p><%= comment.description %></p>
          <%= link_to '', delete_comment_path(@event, comment), data: {:confirm => 'WOOOOW RUDE'}, :method => :delete, class: "glyphicon glyphicon-trash" %>
        <% end %>
      <% else %>
        <h4>Please login to see comments!</h4>
      <% end %>
      <% if current_user %>
        <div class="inner"><%= button_to "Add Comment", new_comment_path, :method => "get", class: "btn btn-small btn-primary"%></div>
      <% end %>
    </div>
  </div>

<hr>

  <div class="row">
    <h2>Who's Going?</h2>
    <% if current_user %>
      <div class="col-xs-12 attendances">
        <% @event.attendances.each do |attendance| %>
        <div class="col-md-3">
          <%= image_tag (attendance.user.profile_image), class: "img-responsive img-circle userpic", size:"140x140" %>
          <p><%= attendance.user.first_name %></p>
          <p>Contributing: <%= attendance.contribution %></p>
        </div>
        <% end %>
      </div>
    <% else %>
      <div class="container">
        <h4>Please login to see who's attending this event!</h4>
      </div>
    <% end %>
  </div>
</div>